repositoryUrl: https://github.com/HakaiInstitute/ocean-data-parser.git
branches:
  - main
  - name: development
    prerelease: true
debug: true
ci: false
dryRun: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
