site_name: Ocean Data Parser - Documentation
theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: light blue
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: light blue
      accent: blue
  features:
    - header.autohide
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow

plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - mike:
      # These fields are all optional; the defaults are as below...
      canonical_version: main
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.scripts.hooks:on_pre_build"
        
markdown_extensions:
    - mkdocs-click

nav:
  - Welcome: index.md
  - Notebooks:
      - Amundsen INT: notebooks/amundsen_int_parser_example.ipynb
      - DFO-BIO parsing: notebooks/bio_odf_parsing_example.ipynb
      - NMEA Parsing: notebooks/nmea_example.ipynb
      - Seabird CNV: notebooks/seabird_cnv_and_btl_example.ipynb
  - Metadata:
      - CF: metadata/cf.md
      - NERC: metadata/nerc.md
      - Polar Data Catalog: metadata/pdc.md
  - Data Parsers:
      - Parsers: parsers/index.md
      - Amundsen: parsers/amundsen-hook.md
      - Fisheries And Ocean Canada:
          - ODF: parsers/dfo/odf-hook.md
          - IOS Shell: parsers/dfo/ios-hook.md
          - P Format: parsers/dfo/p-hook.md
      - ElectricBlue: parsers/electricblue.md
      - NMEA: parsers/nmea.md
      - Onset: parsers/onset.md
      - PME: parsers/pme.md
      - RBR: parsers/rbr.md
      - Seabird: parsers/seabird-hook.md
      - Star-Oddi: parsers/star-oddi.md
      - SunBurst: parsers/sunburst.md
      - Van Essen Instruments: parsers/van-essen-intruments.md
  - CLI: cli.md

extra:
  version:
    provider: mike

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
