site_name: Ocean Data Parser
site_url: https://cioos-siooc.github.io/ocean-data-parser/  

repo_name: ocean-data-parser
repo_url: https://github.com/cioos-siooc/ocean-data-parser

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom
      accent: custom
  custom_dir: docs/theme_override_home/
  features:
    - header.autohide
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select

plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - mike:
      # These fields are all optional; the defaults are as below...
      canonical_version: main
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.scripts.hooks:on_pre_build"
  - search
  - material-plausible
        
markdown_extensions:
    - mkdocs-click
    - admonition
    - attr_list
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Get Started: 
    - Installation: get_started/installation.md
    - How to: get_started/how-to.md
    - Development: get_started/development.md
    - Contributions: get_started/contributions.md
  - User Guide:
    - main: user_guide/index.md
    - odpy (cli): user_guide/odpy.md
    - ocean_data_parser.read: user_guide/read.md
    - ocean_data_parser.parsers:
        - How to: user_guide/parsers/how-to.md
        - amundsen: user_guide/parsers/amundsen.md
        - dfo:
            - odf: user_guide/parsers/dfo/odf.md
            - ios: user_guide/parsers/dfo/ios.md
            - nafc: user_guide/parsers/dfo/nafc.md
        - electricblue: user_guide/parsers/electricblue.md
        - nmea: user_guide/parsers/nmea.md
        - onset: user_guide/parsers/onset.md
        - pme: user_guide/parsers/pme.md
        - rbr: user_guide/parsers/rbr.md
        - seabird: user_guide/parsers/seabird.md
        - star_oddi: user_guide/parsers/star-oddi.md
        - sunburst: user_guide/parsers/sunburst.md
        - van_essen_instruments: user_guide/parsers/van-essen-intruments.md
    - vocabularies: 
        - amundsen: user_guide/vocabularies/amundsen-int.md
        - dfo.odf: user_guide/vocabularies/dfo-odf.md
        - dfo.ios.shell: user_guide/vocabularies/dfo-ios-shell.md
        - dfo.nafc.pfile: user_guide/vocabularies/dfo-nafc-p-files.md
        - seabird: user_guide/vocabularies/seabird.md
  # - Metadata: # TODO 
  #   - CF: metadata/cf.md
  #   - NERC: metadata/nerc.md
  #   - Polar Data Catalog: metadata/pdc.md
  - Example Notebooks:
    - Amundsen INT example: notebooks/amundsen_int_parser_example.ipynb
    - DFO BIO ODF example: notebooks/dfo_bio_odf_parser_example.ipynb
    - DFO BIO NAFC Pfiles example: notebooks/dfo_nafc_p_file_parser_example.ipynb
    - NMEA example: notebooks/nmea_parser_example.ipynb
    - Seabird CNV and BTL files example: notebooks/seabird_cnv_and_btl_parser_example.ipynb


extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cioos-siooc
  generator: false
  analytics:
    provider: plausible
    domain: cioos-siooc.github.io/ocean-data-parser
    src: "https://plausible.server.hakai.app/js/script.js"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
