---

name: Batch Conversion Name
input_path: ""  # path or glob expression of files to convert. It can be a str or a list of str
input_table:  # retrieve files to convert from tables (ignore input_path if set)
  # input_table is used to retrieve files to convert from tables
  # that are listing different glob expressions to retrieve files and associated metadata
  # to append to generated converted files as global attributes (optionnal)
  path: null  # glob expression to retrieve input tables (e.g. 'inputs_tables/*.csv')
  file_column: null  # column use to generate glob expressions used to retrieve source files to parse
  file_column_prefix: ""  # prefix to add to the file_column value
  file_column_suffix: ""  # suffix to add to the file_column value
  add_table_name: false  # retrieve file name and add as table name column
  table_name_column: "table_name"  # column name associated with the file name new column to add table name
  columns_as_attributes: true  # add columns as attributes to the parsed file
  exclude_columns: []  # columns to exclude from the table
exclude: null  # glob expression of files to exclude

parser: null
parser_kwargs: {}

overwrite: false
multiprocessing: 1  # n processes to run [int] or null for all
errors: "ignore"  # raise|ignore
registry:
  path: null  # file_registry(.csv | .parquet)

sentry:
  dsn: Null
  level: INFO
  event_level: WARNING
  traces_sample_rate: 1.0,

# Attributes and Metadata
variable_attributes: {}
global_attributes: {}
file_specific_attributes_path: null  # Path to csv file with one column called "file"
global_attribute_mapping:
  path: null  # Path to csv file (accept glob parameter for multiple files)
  mapping: null  # mapping dataframe
  by: []  # global attributes list
  log_level: WARNING  # [null, WARNING,ERROR] level log when no mapping exist

# Geospatial References
reference_stations:
  path: null
  maximum_distance_from_reference_station_km: null

reference_geograhical_areas:
  path: null

# Transformations
xarray_pipe: []

# QC
ioos_qc: {}
manual_qc: {}

# Outputs
output:
  path: null
  file_name: null
  file_preffix: ""
  file_suffix: ""
  output_format: .nc

summary: null  # Path to save summary file (csv)
