---

name: Batch Conversion Name
input_path: ""  # file or glob expression
exclude: null  # glob expression of files to exclude
parser: null
overwrite: false
multiprocessing: 1  # n processes to run [int] or null for all
errors: "ignore"  # raise|ignore
registry:
  path: null  # file_registry(.csv | .parquet)

sentry:
  dsn: https://cd67597c647c4767adf0b3acf5d3f6a6@o56764.ingest.sentry.io/4505529390137344
  level: INFO
  event_level: WARNING
  traces_sample_rate: 1.0,

# Attributes and Metadata
variable_attributes: {}
global_attributes: {}
file_specific_attributes_path: null  # Path to csv file with one column called "file"
global_attribute_mapping:
  path: null  # Path to csv file (accept glob parameter for multiple files)
  mapping: null  # mapping dataframe
  by: []  # global attributes list
  log_level: WARNING  # [null, WARNING,ERROR] level log when no mapping exist

# Geospatial References
reference_stations:
  path: null
  maximum_distance_from_reference_station_km: null

reference_geograhical_areas:
  path: null

# Transformations
xarray_pipe: []

# QC
ioos_qc: {}
manual_qc: {}

# Outputs
output:
  path: null
  file_name: null
  file_preffix: ""
  file_suffix: ""
  output_format: .nc

summary: null  # Path to save summary file (csv)
