# File input
input:
  - path: tests/parsers_test_files/onset/**/*.csv
    parser: auto
  - path: tests/parsers_test_files/onset/**/*.MON
    parser: auto
file_registry: file_registry.csv

# Log
log:
  file:
    path: batch_conversion.log
    format: null
    level: WARNING
  sentry:
    # https://docs.sentry.io/platforms/python/configuration/options/
    dsn: null
    level: WARNING
    event_level: ERROR
    traces_sample_rate: 1.0,

# Attributes and Metadata
variable_attributes: {}
global_attributes: {}
attribute_corrections:
  file_specific: {}
  global_attribute_mappings: {}

# Transformations
xarray_pipe: []

# QC
ioos_qc: {}
manual_qc: {}

# Outputs
file_output:
  path: null
  overwrite: true
  file_preffix: ""
  file_suffix: _test
  output_format: .nc

upload_to_database:
  name: null
  username: null
  password: null
  table: null
  append: True
  on_conflict: "UPDATE"
