name: Build documentation

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy_docs:
    environment: 
      name: ${{github.ref_name}}
      url: ${{ github.ref == 'main' && 'https://cioos-siooc.github.io/ocean-data-parser/main/' || 'https://cioos-siooc.github.io/ocean-data-parser/dev/' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install the project
        run: uv sync --optional docs
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: |
          if [[ "${{github.ref_name}}" == "main" ]]; then
              uv run mike deploy main --push
          else
              uv run mike deploy dev --push
          fi
          uv run mike set-default main --push
