name: Rebuild mkdocs to gh-pages
on:
  push:
    branches:
      - main
      - development
      - 30-add-mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocstrings[python] mkdocs-jupyter mkdocs-gen-files pandas mike
      - run: |
          if [[ "${{github.ref_name}}" == "main" ]]; then
              mike deploy main --push
          else
              mike deploy dev --push
          fi
