name: Test Package Version Bump

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git tag
          git describe
      - name: Get version difference
        shell: bash
        run: python .github/workflows/review_version_bump.py -b ${{ github.base_ref}}