name: Test package for linter issues and run tests

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - .github/workflows/test-package.yaml
      - setup.py
      - MANIFEST.in
      - ocean_data_parser/**
      - tests/**
  
  push:
    branches:
      - main
      - development
    paths:
      - setup.py
      - MANIFEST.in
      - ocean_data_parser/**
      - tests/**

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev,geo
      - name: ruff check
        run: poetry run ruff check --output-format=github .
      - name: ruff lint
        run: poetry run ruff format --check .
      - name: Review if metadata is updated
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            vocabularies:
              - 'ocean_data_parser/vocabularies/**'
              - 'ocean_data_parser/metatadata/**'
              - 'tests/test_metadata.py'
            changelog:
              - 'CHANGELOG.md'
      - name: Run tests with metadata tests
        if: steps.changes.outputs.vocabularies == 'true'
        run: poetry run pytest -W error::UserWarning --nerc-vocab -n auto
      - name: Run tests without metadata tests
        if: steps.changes.outputs.vocabularies == 'false'
        run: poetry run pytest -W error::UserWarning -k "not test_metadata" -n auto
      - name: Run benchmark
        run: poetry run pytest tests/run_benchmark.py  --benchmark-json output.json
      - name: Update CHANGELOG
        if: steps.changes.outputs.changelog == 'false'
        run: exit 1
        